In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')

In [4]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [5]:
df.shape

(10000, 11)

In [6]:
df.fuel_type.nunique()

3

In [7]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [8]:
df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max()

np.float64(41.2)

In [9]:
df.horsepower.median()

np.float64(254.0)

In [10]:
df.horsepower.mode()

0    252.0
Name: horsepower, dtype: float64

In [11]:
df.mode().iloc[0]

model_year                          1990
origin                               USA
fuel_type                       Gasoline
drivetrain             Front-wheel drive
num_doors                              4
engine_displacement                 2250
num_cylinders                          6
horsepower                         252.0
vehicle_weight                      4270
acceleration                        18.8
fuel_efficiency_mpg                 30.2
Name: 0, dtype: object

In [12]:
filled = df.horsepower.fillna(252.0)

In [13]:
filled.median()

np.float64(252.0)

In [14]:
asia = df[df['origin'] == 'Asia']
subset = asia[['vehicle_weight', 'model_year']].head(7)
subset

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [15]:
X = subset.values
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [16]:
XTX = X.T @ X
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [17]:
XTX_inv = np.linalg.inv(XTX)

In [18]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [19]:
w = XTX_inv @ X.T @ y
w.sum()

np.float64(0.36919696904925486)